spring:
  datasource:
    username: root
    password: 19911A0413@i
    url: jdbc:mysql://localhost:3306/infinity_mart
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*'

sendgrid:
  api:
    keyId: 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
    templateId: d-bd0c175d0a6a492c99e640924528e850
