spring:
  datasource:
    username: root
    password: 19911A0413@i
    url: jdbc:mysql://localhost:3306/infinity_mart
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*'

cart-service:
  messages:
    productAddedCartSuccess: product added to the cart successfully.
    productAddedCartError: Error occured while adding the product to cart.
    quantityUpdateSuccess: product quantity updated successfully.
    quantityUpdateError: Error occured while updating the quantity of the product.
    productDeleteSuccess: product removed from the cart successfully.
    productDeleteError: Error occured while removing the product from the cart.
